# Generated by Django 3.0.2 on 2020-01-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.0, max_length=250)),
                ('moisture', models.FloatField(default=0.0, max_length=250)),
                ('humidity', models.FloatField(default=0.0, max_length=250)),
                ('fanStatus', models.TextField(default='Off', max_length=250)),
                ('lightStatus', models.TextField(default='On', max_length=250)),
                ('action', models.TextField(default='None', max_length=250)),
                ('date', models.DateTimeField(auto_now=True)),
                ('camera', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
