# Generated by Django 2.2.7 on 2020-01-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camerasnaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='devicestatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fansStatus', models.TextField(default='off', max_length=250)),
                ('lightsStatus', models.TextField(default='off', max_length=250)),
                ('waterStatus', models.TextField(default='off', max_length=250)),
                ('seedStatus', models.TextField(default='off', max_length=250)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(default=1)),
                ('moisture', models.IntegerField(default=2)),
                ('humidity', models.IntegerField(default=3)),
                ('summary', models.TextField(default='None', max_length=250)),
                ('refreshRate', models.IntegerField(default=30000)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
