# Generated by Django 3.0.2 on 2020-01-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fansStatus', models.TextField(default='Deactivated', max_length=250)),
                ('lightsStatus', models.TextField(default='Deactivated', max_length=250)),
                ('waterStatus', models.TextField(default='Deactivated', max_length=250)),
                ('seedStatus', models.TextField(default='Deactivated', max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='created_on',
        ),
        migrations.AlterField(
            model_name='sensors',
            name='fanStatus',
            field=models.TextField(default='Deactivated', max_length=250),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='lightStatus',
            field=models.TextField(default='Deactivated', max_length=250),
        ),
    ]
