# Generated by Django 3.0.2 on 2020-01-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_devicestatus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatus',
            name='fansStatus',
            field=models.TextField(default='off', max_length=250),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='lightsStatus',
            field=models.TextField(default='off', max_length=250),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='seedStatus',
            field=models.TextField(default='off', max_length=250),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='waterStatus',
            field=models.TextField(default='off', max_length=250),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='fanStatus',
            field=models.TextField(default='off', max_length=250),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='lightStatus',
            field=models.TextField(default='off', max_length=250),
        ),
    ]
