# Generated by Django 3.0.2 on 2020-01-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20200109_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensors',
            name='fanStatus',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='lightStatus',
        ),
    ]
