# Generated by Django 3.0.2 on 2020-01-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20200109_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='cameraSnaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='action',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='camera',
        ),
    ]
